### ISSUE TITLE
Updating Efficient Exceptions Management

### ISSUE THREAD

**Issue by beeva-franciscoescribano** [beeva/beeva-best-practices#102]
I would like to contribute by adding information about exceptions handling (checked and unchecked) in Code Optimization Best Practices point 
[Efficient Exceptions Management](https://github.com/beeva/beeva-best-practices/blob/master/qa_testing/code_optimization/README.md#efficient-exceptions-management)

**Comment by beeva-luisgonzalez** [comment]
Perfect, go ahead and make a fork, send the PR before this Friday 13, so we can count it for 2016 otherwise your contribution will be taken into account for 2017.

Please also read the contrib guideline and make sure you read them.

**Comment by beeva-franciscoescribano** [comment]
Sorry, but I don't have permission to fork this repository into my account

**Comment by beeva-carlosleon** [comment]
Closed by https://github.com/beeva/beeva-best-practices/pull/105

Thanks for your colaboration!

**Comment by beeva-franciscoescribano** [comment]
You're welcome. I appreciate the work that you are doing
