### ISSUE TITLE
Adding Calabash Example to qa_testing/calabash

### ISSUE THREAD

**Issue by beeva-danielllorente** [beeva/beeva-best-practices#104]
I would like to contribute adding a calabash example using Page Object Pattern

**Comment by beeva-manueldepaz** [comment]
Perfect, go ahead and make a fork, send the PR before this Friday 13, so we can count it for 2016 otherwise your contribution will be taken into account for 2017.

Please also read the contrib guideline and make sure you read them.

**Comment by beeva-manueldepaz** [comment]
merged and closed with PR #107 
Thanks1
