### ISSUE TITLE
/backend/python/ : english revision

### ISSUE THREAD

**Issue by beeva-antonioiglesias** [beeva/beeva-best-practices#106]
After reading this part of the guide, I think I can contribute ...

**Comment by beeva-manueldepaz** [comment]
Remember that all finished issues must be sent as PR before January 13th so they are considered for 2016, otherwise they will be for 2017.

If the PR is already sent and merged, please consider closing this issue.

**Comment by beeva-luisgonzalez** [comment]
#115 received, closing this issue.
