### ISSUE TITLE
Adding small explanation of execution context on beeva-best-practices/backend/scala/

### ISSUE THREAD

**Issue by beeva-brunofollon** [beeva/beeva-best-practices#126]
Since there is a section about Futures in the Scala Best Practices, there should be a section about Execution Contexts to explain what to do in determined cases.

These cases should be handled carefully since Futures can block the main thread if not used adequately.

**Comment by beeva-brunofollon** [comment]
Pull request approved

**Comment by beeva-brunofollon** [comment]
Was not merged yet. My bad

**Comment by CesarGallego** [comment]
Is definitely merged
