### ISSUE TITLE
"Migrate" to static content site

### ISSUE THREAD

**Issue by beeva-carlosleon** [beeva/beeva-best-practices#131]
As we talked by email, we can follow many approaches:

 - Use github webpages
 - Use jekill
 - Use Hugo

This is an open thread for discussion.

Thanks!

**Comment by beeva-carlosleon** [comment]
GitHub Pages sites are subject to the following usage limits:

  -  GitHub Pages source repositories have a recommended limit of 1GB .
  -  Published GitHub Pages sites may be no larger than 1 GB.
  -  GitHub Pages sites have a soft bandwidth limit of 100GB per month.
  -  GitHub Pages sites have a soft limit of 10 builds per hour.

I think we can start by using github web pages, if we met the requirements.

_Source: https://help.github.com/articles/what-is-github-pages/

**Comment by CesarGallego** [comment]
I think that our current approach it's good enough. No limitations, git friendly and widely known.
A best practices guide must be usable over any other consideration. 
My 2 cents: function over form.

**Comment by beeva-juanmanuelperez** [comment]
I agree. 

Let's improve our best practices' contents first, and when everything is perfectly ok, then we can worry about visualization.

Until then, I think our current implementation is good enough.
