### ISSUE TITLE
Upgrading and adding new content to Spark section

### ISSUE THREAD

**Issue by beeva-antonioiglesias** [beeva/beeva-best-practices#139]
I want to upgrade the content of Spark from v1 to the version 2, coordinated with Victor Mendez covering the part of Spark SQL and Structure Streaming mainly.

**Comment by CesarGallego** [comment]
Please, post your response on issue [138](https://github.com/beeva/beeva-best-practices/issues/138) instead open new one.
I'll delete (or you) this issue when you post on the other issue.
Thanks.

**Comment by CesarGallego** [comment]
migrated
