### ISSUE TITLE
analytics/python: Improvements, fixes, suggestions...

### ISSUE THREAD

**Issue by beeva-enriqueotero** [beeva/beeva-best-practices#36]
I've created a fork of this repo to centralize improvements related to analytics/python: https://github.com/beeva-enriqueotero/beeva-best-practices/

Some minor changes I'm working on...
- filling empty sections: scikit-learn, references
- fixing some misspellings or grammar-related mistakes
- formatting, adding images, proper indexing

Some further improvements I suggest:
- info about dependency management: conda vs virtualenv vs docker
- info about deploying models into production
- info about relation with big data: pyspark, etc.
...

Contributions are welcome!

**Comment by beeva-luisgonzalez** [comment]
great!! Thanks a lot Enrique!

**Comment by beeva-robertoandradas** [comment]
I merged @beeva-enriqueotero 's pull request since this issue is referenced. should this issue be closed?. In case more work is needed here then let's keep it open.

**Comment by beeva-luisgonzalez** [comment]
@beeva-robertoandradas you are totally right, it looks like a duped issue so I'm closing it.

thanks!
