### ISSUE TITLE
backend/python: new contributions

### ISSUE THREAD

**Issue by beeva-joaquinnavarro** [beeva/beeva-best-practices#38]
I would like to contribute to the backend/python guide, extending some sections such as Testing (providing more details and recommendations about Mocks) and Programming paradigms (including a subsection about object oriented programming), as well as fixing some grammar mistakes.

**Comment by beeva-luisgonzalez** [comment]
@beeva-joaquinnavarro  go a head, just fork the repo and start working.

Please update this issue when you have questions or with any progress you make!

cheers!

**Comment by beeva-luisgonzalez** [comment]
Remember that all finished issues must be sent as PR before January 13th so they are considered for __2016__,  otherwise they will be for __2017__.

If the PR is already sent and merged, please consider closing this issue.

**Comment by beeva-joaquinnavarro** [comment]
Sorry, I forgot to close the issue when the PR was merged.
