### ISSUE TITLE
analytics/R: improvements, fixes, suggestions...

### ISSUE THREAD

**Issue by beeva-enriqueotero** [beeva/beeva-best-practices#40]
I've created a [fork](https://github.com/beeva-enriqueotero/beeva-best-practices/) of this repo to centralize improvements related to analytics.
At the moment I've only made changes to the _python_ section. But it would be great if we could improve _R_ section also.

Some minor changes I'm working on...
- formatting, adding images, proper indexing
- fixing some misspellings or grammar-related mistakes

Some further improvements I suggest:
- info about deploying models into production
- info about relation with big data: SparkR

Contributions are welcome!

**Comment by beeva-luisgonzalez** [comment]
Awesome as always @beeva-enriqueotero thanks a lot!

**Comment by beeva-luisgonzalez** [comment]
Remember that all finished issues must be sent as PR before January 13th so they are considered for __2016__,  otherwise they will be for __2017__.

If the PR is already sent and merged, please consider closing this issue.

**Comment by beeva-carlosleon** [comment]
Closed by https://github.com/beeva/beeva-best-practices/pull/99

Thanks!
