### ISSUE TITLE
unitTesting/NodeJS: new contributions

### ISSUE THREAD

**Issue by beeva-juanramonrivero** [beeva/beeva-best-practices#41]
I would like to contribute to the unitTesting/NodeJS guide, extending this section with Sinon & Proxyquire libraries and fix "TDD with Mocha" I think this test are Integration Testing, no Unit Testing.

**Comment by beeva-luisgonzalez** [comment]
@beeva-juanramonrivero  please update the description of this issue, you should include what is the specific changes/imporvements you want to make!

**Comment by beeva-luisgonzalez** [comment]
@beeva-juanramonrivero  thanks for the update!

Feel free to make a fork and send us a PR when you are done!

If you have any questions or comments, or just want to update us on the progress of this issue post a message!

**Comment by beeva-manueldepaz** [comment]
Done!

**Comment by beeva-manueldepaz** [comment]
[Done!](https://github.com/beeva/beeva-best-practices/pull/47)
