### ISSUE TITLE
gitProject/Git: new contributions

### ISSUE THREAD

**Issue by beeva-josedejuan** [beeva/beeva-best-practices#42]
I would like to contribute aggregating a new section called “Working in a git project”. It will describe the main sections (working directory, staging area, .git directory, remote repository) in a git project and useful commands like clone, add, commit, checkout, push, merge, branch, stash, reset, diff, log.

Issue State:
- Main sections of Git repository: Done
- Git commands: Done

Pull Request created

**Comment by beeva-cesarsilgo** [comment]
Thank you Jose! You can fork the repository and make a pull request when finished.

**Comment by beeva-luisgonzalez** [comment]
@beeva-josedejuan please keep udpated this issue with any progress you make, as other may join you in the middle of this task, if you have any comments or want to discuss anything this is also the place to do it!

**Comment by beeva-luisgonzalez** [comment]
Aceptado y cerramos tu PR. #46
