### ISSUE TITLE
big_data/redshift: new contributions 

### ISSUE THREAD

**Issue by beeva-arturomartinez** [beeva/beeva-best-practices#48]
I would like to contribute filling TBD sections:
- Loading Data
- User Defined Functions
- Security
- Authentication and Authorization
- Encryption

Also I will add some content to _Workload Management_ section

**Comment by beeva-luisgonzalez** [comment]
@beeva-arturomartinez  go a head, just fork the repo and start working.

Please update this issue when you have questions or with any progress you make!

**Comment by beeva-arturomartinez** [comment]
Finished & Merged
