### ISSUE TITLE
nosql/mongodb: new contributions

### ISSUE THREAD

**Issue by BEEVA-JulioMartinez** [beeva/beeva-best-practices#49]
Hello,

I'd like to contribute with a new section of best practices for MongoDB.

**Comment by beeva-luisgonzalez** [comment]
@BEEVA-JulioMartinez  go a head, just fork the repo and start working.

Do you have any contributions to the MongoDB document you want to discuss?

Please update this issue when you have questions or with any progress you make!

**Comment by JulianCobas** [comment]
Hi, 
I am interested in contributing information related with MongoDB and i have seen that you are starting a new section about this. @BEEVA-JulioMartinez, on what part of MongoDB want to focus? Developer or DBA? On the other hand, when do you expect to open this section on MongoDB?

**Comment by BEEVA-JulioMartinez** [comment]
Hi @JulianCobas 
I've been working on this and i've uploaded my advances and some points that i have on my mind. Take a look on it in my repo: https://github.com/BEEVA-JulioMartinez/beeva-best-practices/tree/master/nosql/mongodb to see the points i'm working on.

If you have any suggestions or want to collaborate with other points, you aer welcome. I've added you to the repository.

**Comment by JulianCobas** [comment]
Hi @BEEVA-JulioMartinez ,

I've added a new section related to the storage engine.  I'm working now on a short summary of the CRUD operations. I hope it will be ready next week.

Best regards!

**Comment by BEEVA-JulioMartinez** [comment]
Hi,
I've finished te points that i had opened. 
@JulianCobas i've modified "memory use" of WiredTiger Storage Engine to be more explicit about the use in each version,  because it has changed in every version. How are you going with the CRUD operations?

**Comment by BEEVA-JulioMartinez** [comment]
Hello,

We have finished and done the [PR](https://github.com/beeva/beeva-best-practices/pull/81)

**Comment by beeva-manueldepaz** [comment]
done, closed with PR #81
