### ISSUE TITLE
One time bindings in Angular

### ISSUE THREAD

**Issue by beeva-williamsaguilera** [beeva/beeva-best-practices#51]
Talk about one time bindings in AngularJS and when they should be used to improve the application's performance, and lower the digest time.

**Comment by beeva-manueldepaz** [comment]
Thanks @beeva-williamsaguilera !
If you wish to help in this area make an specific fork and PR according: https://github.com/beeva/beeva-best-practices#contrib-guidelines

**Comment by beeva-manueldepaz** [comment]
Maybe it's good idea to include in #57
