### ISSUE TITLE
backend/nodeJS: ES6

### ISSUE THREAD

**Issue by beeva-najim** [beeva/beeva-best-practices#53]
I would like to contribute to refactor all the code to ES6. Your welcome  if you want to help me :)

**Comment by beeva-manueldepaz** [comment]
Thanks @beeva-najim !
Use a fork to contribute as follows https://github.com/beeva/beeva-best-practices#contrib-guidelines

**Comment by beeva-carlosleon** [comment]
Closed

**Comment by beeva-manueldepaz** [comment]
Hi,

Best we're going to move the arrow example to Javascript main general section, and continue with your idea @beeva-najim, in order to refactor all the js code in node section to ES6.

i.e.
* express code example (const,let instead var, arrows, ..)
* hapi (arrow functions)
* any other :)
