### ISSUE TITLE
Quality Assurance / Cucumber

### ISSUE THREAD

**Issue by beeva-alvarocanada** [beeva/beeva-best-practices#55]
I would like to contribute to best practices with some explanation and tips about Cucumber framework :D.
Also I fix some typos I found while was reviewing ATDD and BDD sections.

**Comment by beeva-manueldepaz** [comment]
Thanks @beeva-alvarocanada !
Use a fork to contribute as follows https://github.com/beeva/beeva-best-practices#contrib-guidelines

**Comment by beeva-cesarsilgo** [comment]
Your Pull Request has been merged.

Thanks!
