### ISSUE TITLE
AngularJS - Improve best practices including Webpack & ES6, Components, Component Based Architecture, Routable Components, & Redux.

### ISSUE THREAD

**Issue by beeva-pablohidalgo** [beeva/beeva-best-practices#57]
Hi, 

I would like to contribute to AngularJS best practices updating the available documentation including:

- How to add & use ES6 features with Webpack (modules, arrow syntax, variable destructuring, default parameters,  best practices, how to improve our architecture, etc...) on our AngularJS APP.

- What are components, how to use them, and how to architecture our application with them.

- Routable components through ui-router (good bye controllers!)

- Directory/folder structure for manage all this.

- Update to AngularJS 1.6.

Thanks!

**Comment by beeva-cesarsilgo** [comment]
Thanks @beeva-pablohidalgo !
Please use a fork to contribute as follows https://github.com/beeva/beeva-best-practices#contrib-guidelines

**Comment by beeva-manueldepaz** [comment]
Hi @beeva-pablohidalgo good idea!

There are more people interested in update the angular area, coordinate with @beeva-williamsaguilera to make one fork.

Thanks!

**Comment by beeva-manueldepaz** [comment]
merged! #71
