### ISSUE TITLE
backend/scala: sbt build tool

### ISSUE THREAD

**Issue by beeva-pablojimenez** [beeva/beeva-best-practices#59]
I would like to contribute by adding more information and examples about SBT as build tool for scala projects

**Comment by beeva-carlosleon** [comment]
Hi @beeva-pablojimenez,

Use a fork to contribute as follows https://github.com/beeva/beeva-best-practices#contrib-guidelines

Thanks!

**Comment by beeva-luisgonzalez** [comment]
Remember that all finished issues must be sent as PR before January 13th so they are considered for __2016__,  otherwise they will be for __2017__.

If the PR is already sent and merged, please consider closing this issue.

**Comment by beeva-luisgonzalez** [comment]
PR merged!
