### ISSUE TITLE
Cloud/aws : New contribution

### ISSUE THREAD

**Issue by beeva-adrianvegas** [beeva/beeva-best-practices#61]
I would like to contribute by adding information about RDS service best practices.

**Comment by beeva-cesarsilgo** [comment]
Thanks @beeva-adrianvegas !
Please use a fork to contribute as follows https://github.com/beeva/beeva-best-practices#contrib-guidelines

**Comment by beeva-adrianvegas** [comment]
Pull request merged. [#79](https://github.com/beeva/beeva-best-practices/pull/79) .
