### ISSUE TITLE
Include Ember.js good practices

### ISSUE THREAD

**Issue by beeva-juanantoniogomez** [beeva/beeva-best-practices#72]
Hello,

We'd like to contribute with a new section of best practices for Ember.js

Contributors:
* Julián Pérez Sampedro
* Juan Antonio Gómez Benito
* Iván de Gracia Moreno
* Adrián González Rus

Regards,

**EDIT**: Add Adrián to the issue.

**Comment by beeva-manueldepaz** [comment]
Thanks @beeva-juanantoniogomez @beeva-julianperez @beeva-ivandegracia !

Please use a fork to contribute as follows https://github.com/beeva/beeva-best-practices#contrib-guidelines

**Comment by beeva-manueldepaz** [comment]
Thanks @beeva-juanantoniogomez !
Don't forget to link in the main [README.md](../blob/master/README.md)

**Comment by shokmaster** [comment]
@beeva-manueldepaz done!
PR opened, ready to merge: https://github.com/beeva/beeva-best-practices/pull/85

**Comment by beeva-luisgonzalez** [comment]
Remember that all finished issues must be sent as PR before January 13th so they are considered for __2016__,  otherwise they will be for __2017__.

If the PR is already sent and merged, please consider closing this issue.
