### ISSUE TITLE
Updating footer

### ISSUE THREAD

**Issue by beeva-manueldepaz** [beeva/beeva-best-practices#82]
We need help to update all the footer across the whole guide.

Using: 
````markdown
[BEEVA](https://www.beeva.com) | Technology and innovative solutions for companies
```` 

Instead
````markdown
[BEEVA](https://www.beeva.com) | 2016, 2017,...
````

**Comment by beeva-carlosleon** [comment]
I can help you :)

**Comment by beeva-carlosleon** [comment]
I have done inside one pull request i had prepared https://github.com/beeva/beeva-best-practices/pull/87. Take a look because i have all changed by:
___

[BEEVA](https://www.beeva.com) | Technology and innovative solutions for companies

Because i normally use a separator in footers.
Thanks!

**Comment by beeva-luisgonzalez** [comment]
Remember that all finished issues must be sent as PR before January 13th so they are considered for __2016__,  otherwise they will be for __2017__.

If the PR is already sent and merged, please consider closing this issue.

**Comment by beeva-manueldepaz** [comment]
Thanks a lot @beeva-carlosleon 
Much better with separator!

I'm using PR for almost every contribution, except those that are minor format changes. 
In this case, probably I would have used direct commits, but the guideline say PR.
