### ISSUE TITLE
/backend/java : English revision

### ISSUE THREAD

**Issue by beeva-juanmanuelperez** [beeva/beeva-best-practices#83]
Time to review english for this guide

**Comment by beeva-manueldepaz** [comment]
Thanks @beeva-juanmanuelperez !
Use PR as in your other contributions.

I assume you are going to do these enhancements. to use labels and Assignees, but don't hesitate to change it if apply.

**Comment by beeva-luisgonzalez** [comment]
Remember that all finished issues must be sent as PR before January 13th so they are considered for __2016__,  otherwise they will be for __2017__.

If the PR is already sent and merged, please consider closing this issue.

**Comment by beeva-luisgonzalez** [comment]
I'm closing this issue as I think is related to PR #68

**Comment by beeva-juanmanuelperez** [comment]
Careful!! the PR in #68 was for agile section, and this is for the JAVA guide. I think it is better to open a different issue/PR for each revisited guide, as I don't really know how many of them will I be able to complete before January 13th
