### ISSUE TITLE
front-end tools - Grunt and Gulp contributions

### ISSUE THREAD

**Issue by beeva-davidherranz** [beeva/beeva-best-practices#84]
I would like to contribute to the grunt/gulp front-end guide, including the plugins related to the EcmaScript 6 transpilations to a more browser-friendly JavaScript, as well as adding more plugins and fixing some grammar mistakes.

Should I create two separated issues, one for Grunt and one for Gulp?

**Comment by beeva-manueldepaz** [comment]
Thanks @beeva-davidherranz !
Don't worry, both are related with frontend tooling, so include it on a single PR.

Please use a fork to contribute as follows https://github.com/beeva/beeva-best-practices#contrib-guidelines

**Comment by beeva-davidherranz** [comment]
It is done @beeva-manueldepaz 

PR #89 ready to be merged

**Comment by beeva-luisgonzalez** [comment]
Remember that all finished issues must be sent as PR before January 13th so they are considered for __2016__,  otherwise they will be for __2017__.

If the PR is already sent and merged, please consider closing this issue.

**Comment by beeva-luisgonzalez** [comment]
PR #89  is merged, so I'm closing this issue.
