### ISSUE TITLE
Add SOLID principles to code design section

### ISSUE THREAD

**Issue by beeva-carlosleon** [beeva/beeva-best-practices#86]
Hi,

I am going to collaborate adding this information by creating a fork.

Thanks

**Comment by beeva-carlosleon** [comment]
Hi,
I have created this PR: https://github.com/beeva/beeva-best-practices/pull/87

Thanks!

**Comment by beeva-carlosleon** [comment]
I have accepted this PR, please take a look if something is wrong.

Thanks!

**Comment by beeva-luisgonzalez** [comment]
If the PR is merged, please consider closing this issue.

**Comment by beeva-carlosleon** [comment]
Yeah, there is no problems merging and i added the footer to all the guide also with the footer section.
