### ISSUE TITLE
Broken Links to Sonar

### ISSUE THREAD

**Issue by beeva-estebandorado** [beeva/beeva-best-practices#92]
I had checked all pages to search some information about Sonar and find 2 broken links:

* line 108 in file https://github.com/beeva/beeva-best-practices/blob/886d2c20e53c2a76d4a87e8ee1d3a577876e24b7/devops/git/README.md#push-only-finished-and-tested-code

* Line 214 in file https://github.com/beeva/beeva-best-practices/blob/886d2c20e53c2a76d4a87e8ee1d3a577876e24b7/qa_testing/code_design/README.md#naming-and-format

I send a PR with information about Sonar and I will fix this broken links about Sonar.

**Comment by beeva-luisgonzalez** [comment]
I'm closing this issue, since the PR is merged, thanks!
